# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pull Request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Install ${{ matrix.node-version }}
      uses: borales/actions-yarn@v4
      with:
        node-version: ${{ matrix.node-version }}
        cmd: install
    - name: Build
      uses: borales/actions-yarn@v4
      with:
        cmd: build
    - name: Test
      uses: borales/actions-yarn@v4
      with:
        cmd: test
